Repository CareLuLu/react-native-web-ui-components, pull requests merged in 2019-04, with the labels that each got.

#1 fix(dropzone): allow to accept */* on web
  package.json
  src/Dropzone/index.web.js
  src/Helmet/index.web.js
  src/Icon/index.web.js
Labels: bug

#4 fix(link): remove amp invalid attribute
  package.json
  src/Link/index.web.js
Labels: [zube]: In Progress, bug

#5 Feature/hr
  .gitignore
  src/Hr/index.js
  src/index.js
  yarn.lock
Labels: [zube]: In Progress, enhancement

#8 fix(hrComponent): fix conditional statement for showing center text o…
  src/Hr/index.js
Labels: bug
